REM INSERTING into XXFLK_CATEGORY_ANALYTICS
SET DEFINE OFF;
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (1,'2017-11-17','SPORTIV',100000,50000,200,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (2,'2017-11-17','MUZICA',300000,30000,500,10,'DECHATLON',6000,'WORLDCLASS',1444,'HERVIS',611,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (3,'2017-10-26','SPORTIV',70000,5000,140,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (4,'2017-09-16','SPORTIV',70000,5000,140,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (5,'2017-08-16','SPORTIV',60000,4000,110,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (6,'2017-07-16','SPORTIV',50000,3000,90,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (7,'2017-06-16','SPORTIV',40000,2000,50,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
Insert into XXFLK_CATEGORY_ANALYTICS ( id , day_date , category_code , total_exp , avg_basket_size , clients_nr , client_perc , top_player_1 , top_player_1_value , top_player_2 , top_player_2_value , top_player_3 , top_player_3_value , last_update_date ) values (8,'2017-10-16','SPORTIV',80000,6000,170,5,'DECHATLON',4000,'WORLDCLASS',444,'HERVIS',111,curdate());
REM INSERTING into XXFLK_CUSTOMER_CATEGORIES
SET DEFINE OFF;
Insert into XXFLK_CUSTOMER_CATEGORIES ( id , code , description , data_in , data_out , creation_date , created_by , last_update_date , last_updated_by ) values (1,'SPORTIV','Sportiv',curdate(),null,curdate(),'admin',curdate(),'admin');
Insert into XXFLK_CUSTOMER_CATEGORIES ( id , code , description , data_in , data_out , creation_date , created_by , last_update_date , last_updated_by ) values (2,'MUZICA','Muzica',curdate(),null,curdate(),'admin',curdate(),'admin');
REM INSERTING into XXFLK_DEPARTMENT_STORES
SET DEFINE OFF;
Insert into XXFLK_DEPARTMENT_STORES ( id , code , description , category_code, subcategory_Code, data_in , data_out , creation_date , created_by , last_update_date , last_updated_by ) values (2,'Dechatlon','Dechatlon','SPORTIV', 'RETAIL','2017-11-16',null,curdate(),'admin',curdate(),'admin');
REM INSERTING into XXFLK_RETAILER_ANALYTICS
SET DEFINE OFF;
Insert into XXFLK_RETAILER_ANALYTICS ( id , day_date , department_store , share_perc , clients_nr , churn , next_month_tx , new_customers , next_year_tx , last_update_date ) values (1,'2017-11-17','DECHATLON',20,6000,30,20000,200,2000000,to_timestamp('2017-11-17 10:16:05.0','null'));
